# Generated by Django 4.2.1 on 2023-05-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topTenGames', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gaem',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
